[versions]

shadow = "8.3.0"
kotlin = "2.2.21"
kotlinx-coroutines-core = "1.10.2"
kotlinx-atomicfu = "0.29.0"
paper = "1.21.8-R0.1-SNAPSHOT"
velocity = "3.4.0-SNAPSHOT"
messenger = "0.0.1"

worldedit = "7.3.0"
protocollib = "5.4.0"
packetevents = "2.9.5"

[libraries]

# Gradle plugins

plugin-shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
plugin-kotlin-jvm = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-kapt = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
plugin-kotlin-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu-gradle-plugin", version.ref = "kotlinx-atomicfu" }
plugin-nyaadanbou-conventions = { group = "cc.mewcraft.gradle", name = "conventions", version = "1.0-SNAPSHOT" }

# Code dependencies

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-atomicfu = { group = "org.jetbrains.kotlinx", name = "atomicfu", version.ref = "kotlinx-atomicfu" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
messenger = { group = "cc.mewcraft.messenger", name = "common", version.ref = "messenger" }

worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version.ref = "worldedit" }
protocollib = { group = "com.comphenix.protocol", name = "ProtocolLib", version.ref = "protocollib" }
packetevents = { group = "com.github.retrooper", name = "packetevents-spigot", version.ref = "packetevents" }

[plugins]

pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }